name: spotify_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  bloc_test: ^9.1.7
  go_router: ^13.2.4
  get_it: ^7.7.0
  internet_connection_checker: ^1.0.0+1
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  mockito: ^5.4.4
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.4.0
  shimmer: ^3.0.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  async: ^2.11.0
  url_launcher: ^6.2.6
  realm: ^2.1.0
  stream_transform: ^2.1.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
